# Generated by Django 4.1.1 on 2022-10-26 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('main_contact', models.CharField(blank=True, max_length=12, null=True)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('otp_isValid', models.BooleanField(default=False)),
                ('otp_timestamp', models.DateTimeField(default=datetime.datetime(2022, 10, 26, 0, 37, 15, 951890))),
            ],
        ),
    ]
