# Generated by Django 4.1.2 on 2022-10-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_otp_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_timestamp',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_stamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
