# Generated by Django 4.1.2 on 2022-10-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_name_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_isValid',
        ),
    ]
